### ISSUE TITLE
GCC error when compling: directive writing up to 127 bytes into a region of size 41

### ISSUE THREAD

**Issue by Jubilee101** [pgmoneta/pgmoneta#107]
**Describe the bug**

When compiling the project, I got the following error: 
```
/home/fedora/pgmoneta/src/libpgmoneta/se_s3.c:252:17: 
error: ‘%s’ directive writing up to 127 bytes into a region of size 41 [-Werror=format-overflow=]
  252 |    key_length = sprintf(key, "AWS4%s", config->s3_secret_access_key);
```
**GCC info**
My gcc version is gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)

I suppressed the bug by increasing the key size, but there should be a better way to do this.

**Comment by jesperpedersen** [comment]
@MariamFahmy98 Can you rewrite all the `sprintf` statements into `pgmoneta_append` based ones for `se_azure.c` and `se_s3.c` ?

**Comment by MariamFahmy98** [comment]
> @MariamFahmy98 Can you rewrite all the `sprintf` statements into `pgmoneta_append` based ones for `se_azure.c` and `se_s3.c` ?

Sure, I'll start working on it.

**Comment by resyfer** [comment]
@jesperpedersen @MariamFahmy98 would it be fine to convert them to snprintf? I had already applied a fix to the given problem using `snprintf` while working on an issue to limit the characters:

```c
key = malloc(4 + 40 + 1);
key_length = snprintf(key, 4 + 40 + 1, "AWS4%s", config->s3_secret_access_key);
```

though `pgmoneta_append` would definitely work good, but I think it would also require an additional check for 40 characters length for AWS S3 secret access key.

**Comment by jesperpedersen** [comment]
I think it is better to use `pgmoneta_append` and friends, and then do an explicit length check - using `snprintf` will just cut any remaining characters.

**Comment by jesperpedersen** [comment]
@MariamFahmy98 - *cough*
