### ISSUE TITLE
Native backup

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#123]
Replace `pg_basebackup` with a native solution based on the replication protocol

**Comment by jesperpedersen** [comment]
@Jubilee101 Please, fill this out

**Comment by Jubilee101** [comment]
> @Jubilee101 Please, fill this out

Uhh just to make sure, you mean with commits right? Or do I need to put doc here?

**Comment by jesperpedersen** [comment]
It should be the brief summary of your doc

**Comment by Jubilee101** [comment]
Currently pgmoneta generates backups by sending pg_basebackup command to Postgres database server. We want to rid of this dependency on Postgres binaries by implementing the process this command triggers. This roughly involves:

1. Sending the BASE_BACKUP command to the server.
2. Implementing the Streaming Replication Protocol to receive the backup and the necessary write-ahead log.
3. Saving the backup locally, verifying checksum and performing compression if necessary.

**Comment by Jubilee101** [comment]
Hey should we close this issue? Or do we want to use this for more advanced backups as well?
