### ISSUE TITLE
Dashboard for pgmoneta metrics

### ISSUE THREAD

**Issue by linzs148** [pgmoneta/pgmoneta#133]
design dashboard for current pgmoneta metrics

**Comment by linzs148** [comment]
dashboard screenshots

overall
![overall](https://github.com/pgmoneta/pgmoneta/assets/56420840/5e9df97d-db83-4c49-84e1-41df5c158edb)

server
![server](https://github.com/pgmoneta/pgmoneta/assets/56420840/035cf012-8006-464a-8c2d-d012e0f20574)

backup
![backup](https://github.com/pgmoneta/pgmoneta/assets/56420840/aa8e840e-7070-4eb2-af49-b9c8b0a88eec)

wal
![wal](https://github.com/pgmoneta/pgmoneta/assets/56420840/fbca4e02-34de-4c90-9b25-35f9790e4454)

**Comment by jesperpedersen** [comment]
@linzs148 Could you get this sorted such we can merge this first part ?

**Comment by jesperpedersen** [comment]
I'm closing this one - improvements can be done in new issues
