### ISSUE TITLE
WAL Shipping

### ISSUE THREAD

**Issue by Jubilee101** [pgmoneta/pgmoneta#151]
**Is your feature request related to a problem? Please describe.**

We want to ship the WAL segments received from Postgres server to another server other than the backup server. So that we can do point-in-time recovery using an older backup with the shipped WAL segments if the backup server crashes.

**Describe the solution you'd like**

It would be easy to first add an configuration to ship the segments to a local directory. And then we should move on to remote server shipping, we can probably look at ssh, sftp or scp. We should probably also cleanup out-dated segments.

**Comment by Jubilee101** [comment]
Hi @jesperpedersen ,  #152 is adding a new wal_shipping option in the configuration as we talked about. Currently it merely assumes that the address is local and write a copy of WAL segments to that local directory. I added a new tutorial to illustrate that. We can look at remote shipping once this is sorted out. Also I feel that the option should be for each server seperately, since we receive WAL segments from different servers seperately. 

As for cleanup, I took a look at wf_delete and I don't see any wal cleanup codes... I don't know if I missed any. I think one of the hard point is that wal segments name doesn't reflect timestamp, so it's not easy to know which segments is older than the backup, we should probably keep an info file for that.

**Comment by jesperpedersen** [comment]
You have to follow `pgmoneta_delete_wal(int srv);`

**Comment by Jubilee101** [comment]
Sorry about the delay, I refactored pgmoneta_delete_wal(int srv) a little so that it also deletes wal segments under wal_shipping. As for prometheus, I'm not quite sure how much info we should disclose, right now I account the size of wal segments under wal_shipping into the total size as well as the total wal size.

**Comment by jesperpedersen** [comment]
You are right about the Prometheus metrics.

I think we need

```
pgmoneta_wal_shipping(name)
pgmoneta_wal_shipping_used_space
pgmoneta_wal_shipping_free_space
pgmoneta_wal_shipping_total_space
```

as new metrics for this.

If they are not used then they are `0`

**Comment by Jubilee101** [comment]
Just a few questions:

> pgmoneta_wal_shipping(name)
What is name here?

> pgmoneta_wal_shipping_free_space
How are we supposed to know how much free space there is? Are we putting a limit to the size of shipping directory?

> pgmoneta_wal_shipping_total_space
Is total_space = used_space + free_space?

Also is the metrics per server or all servers combined?

**Comment by jesperpedersen** [comment]
`name` is the name of the server in question.

Just use `pgmoneta_free_space` and `pgmoneta_total_space` - and per server

**Comment by jesperpedersen** [comment]
It is basically a copy'n'paste from  the "main" metrics

**Comment by Jubilee101** [comment]
Metrics added, except for pgmoneta_wal_shipping(name), I thought it was the address, turns out prometheus doesn't allow strings in the panel, so now I'm a little confused.

**Comment by jesperpedersen** [comment]
Look around prometheus.c#773 and prometheus.c#813

**Comment by Jubilee101** [comment]
Oh yeah I got that. `pgmoneta_wal_shipping_used_space`, `pgmoneta_wal_shipping_free_space` and `pgmoneta_wal_shipping_total_space` have been added. But is `pgmoneta_wal_shipping` also a metric? I used think it's for the shipping address, but prometheus doesn't allow string apparently.

**Comment by jesperpedersen** [comment]
```
pgmoneta_wal_shipping(name)  -- size of the WAL shipping for the server
pgmoneta_wal_shipping_used_space -- size of everything under the WAL shipping directory; this could include archives
pgmoneta_wal_shipping_free_space -- free size of the WAL shipping directory for the server
pgmoneta_wal_shipping_total_space -- total size of the WAL shipping directory for the server
```

But we can discuss that... it depends on how automated we want the WAL shipping infrastructure to be.

I'll take a deeper look at your patch tomorrow

**Comment by jesperpedersen** [comment]
F.ex.

```
[server1]
wal_shipping = /mnt/backup

[server2]
wal_shipping = /mnt/backup
```

would create

```
/mnt/backup/server1/wal
/mnt/backup/server2/wal
```

but there could be

```
/mnt/backup/server1/archives
/mnt/backup/server2/archives
```

as well...

**Comment by Jubilee101** [comment]
Hmm so are we thinking about shipping the base backups as well? Then should it still be named **wal**_shipping?

**Comment by jesperpedersen** [comment]
No, it is only for the WAL - the rest is up to the user to setup

**Comment by Jubilee101** [comment]
Oh I see, right now I leave the user to make sure that the directory for each server is unique. It is not a bad idea I think, less burden for the user. Also I think our way of calculating free space and total space is for a whole file system, not a particular directory, are we having these metrics because in the future we are supporting remote wal shipping, with another file system/disk space?

**Comment by jesperpedersen** [comment]
Well, we can make it explicit for WAL only.

The `free` and `total` is to monitor if the disk is running out - such that the WAL can't be copied...

We can always change it later if the directories are managed by pgmoneta or not - just make sure that the documentation is clear on what is expected from the user, and what the metrics means

**Comment by Jubilee101** [comment]
Sorry for the delay. I changed the wal_shipping behavior as you suggested -- now the segments will be saved under /server1/wal/ subdirectory. The doc and prometheus is updated accordingly as well.
