### ISSUE TITLE
Verify replication slots upon startup

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#157]
We should verify that `backup_slot` and `wal_slot` are valid on the server in question.

If not, then it is a FATAL and pgmoneta should be stopped.

**Comment by jesperpedersen** [comment]
F.ex.

```
postgres=# SELECT slot_name, slot_type FROM pg_replication_slots;
 slot_name | slot_type 
-----------+-----------
 repl      | physical
(1 row)
```

**Comment by Jubilee101** [comment]
Got it! I'll work on this. One problem we found constantly is missing WAL segments when there's no replication slot configured. Currently we do nothing when there is no replication slot configured. Should we make wal_slot a required configuration? Or can we create a replication slot automatically for user if there's none?

**Comment by jesperpedersen** [comment]
I added #160 for the first part, and #161 for the latter

**Comment by Jubilee101** [comment]
Got it!
