### ISSUE TITLE
Exclude backup_label.old from the backup

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#170]

**Comment by hzhang-vibrant** [comment]
Hi Jesper, could you elaborate on this?

**Comment by Jubilee101** [comment]
Hi Jesper, could you elaborate on this?

**Comment by jesperpedersen** [comment]
Its a file in the top-level directory that we should not include in the backup

**Comment by hzhang-vibrant** [comment]
May I ask under what circumstances will I see this file? I checked our backup and there is only `backup_label`, and our restore process removes this file automatically. I also checked the backup after the server successfully started on it, and still no sign of `backup_label.old`. 

Also I'm curious why do we not need `backup_label` in the first place? I took a look at it and it contains info such as where the wal starts... seems pretty essential.

**Comment by Jubilee101** [comment]
May I ask under what circumstances will I see this file? I checked our backup and there is only backup_label, and our restore process removes this file automatically. I also checked the backup after the server successfully started on it, and still no sign of backup_label.old.

Also I'm curious why do we not need backup_label in the first place? I took a look at it and it contains info such as where the wal starts... seems pretty essential.

**Comment by jesperpedersen** [comment]
Yeah, we need to keep `backup_label` around, and ideally verify it against `pg_control`.

The easiest way to create the `baclup_label.old` file is do a backup of a replica server

**Comment by jesperpedersen** [comment]
Yeah, I noticed - I have removed `_exists_file` in the patch I'm working on

**Comment by jesperpedersen** [comment]
You can remove it as well in your pull request

**Comment by Jubilee101** [comment]
It is already removed in #172
