### ISSUE TITLE
Rate limit: Network

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#196]
Provide a rate limit (global and server) to limit network traffic.

This is for backup

**Comment by jesperpedersen** [comment]
@shikharish It is about making sure that pgmoneta only send network requests to the server at the defined rate limit - f.ex. 512 kb/s.

Follow `backup.c`, `wf_backup.c` and friends

**Comment by shikharish** [comment]
@jesperpedersen I have been trying to solve this issue for the past week and had a few questions. The solution is not clear to me yet. I wanted to get some of your inputs.
- I believe the implementation would be in the `pgmoneta_consume_copy_stream_start()` function(or `pgmoneta_read_copy_stream()` to be precise)?
- I think the logic would be to let pgmoneta backup data with as much bandwidth as possible at the start of an interval, and then block transfer for a calculated amount of time so as to average out the desired rate. Although I am not sure exactly how to implement this right now.

**Comment by jesperpedersen** [comment]
Yes, you have to work your way through `wf_backup.c` and make sure that f.ex. `pgmoneta_consume_data_row_messages()` supports the rate limit. However, note that `pgmoneta_consume_data_row_messages()` is also used by `wal.c` which should not be rate limited.

Yeah, you need to define a "window" and then measure the bytes received within it, maybe you can get some ideas from https://stackoverflow.com/questions/13557858/c-linux-bandwidth-throttling-of-application

**Comment by jesperpedersen** [comment]
It is to get the entire message. You can read about the message formats here

https://www.postgresql.org/docs/devel/protocol-message-formats.html

**Comment by jesperpedersen** [comment]
https://www.postgresql.org/docs/current/protocol-replication.html

**Comment by GuChad369** [comment]
A rate limit utility has been implemented in this [PR](https://github.com/pgmoneta/pgmoneta/pull/227). You can use the token bucket algorithm from that implementation as a method to enforce this network limit.
