### ISSUE TITLE
Rate limit: Disk

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#197]
Provide a rate limit (global and server) to limit disk I/O traffic.

This is for backup

**Comment by GuChad369** [comment]
For this issue, I have some basic ideas:
1. Set a rate limit globally and per server.
2. Create a function to measure the rate.
3. During the I/O process, fork a child process to check its value against the rate limit. If it exceeds the limit, use usleep() or send a signal to slow down the process.
Is this approach correct or naive? Could I get some help on which files might be involved?

**Comment by jesperpedersen** [comment]
It should be handled in-process for the backup process. And, its `wf_backup.c` and friends.

**Comment by GuChad369** [comment]
Is this [part](https://github.com/pgmoneta/pgmoneta/blob/f13ae08e5020e4bd36964060588b41b23d34a8bf/src/libpgmoneta/message.c#L2511-L2523) actually performing the write to disk? If we are implementing rate limiting, should we do it during this phase?

I plan to use the `token bucket algorithm` here to limit the rate. Is this possible?

**Comment by jesperpedersen** [comment]
Correct

**Comment by GuChad369** [comment]
Can we use GCC built-in functions `like __sync_bool_compare_and_swap` in the code? Since it involves multithreading, I want to make it lockless for efficiency. Is this approach allowed?

**Comment by jesperpedersen** [comment]
Use `#include <stdatomic.h>`
