### ISSUE TITLE
Expose WAL filename in the Prometheus interface

### ISSUE THREAD

**Issue by shikharish** [pgmoneta/pgmoneta#200]
Exposing the current WAL filename to the Prometheus metrics is a useful feature.

Such as:
```
pgmoneta_current_wal_file{server="XYZ", file="000000010000000000000027.partial"} 1
```

**Comment by shikharish** [comment]
Currently the approach I have thought of is: 
- Get the wal directory of a server
- Get the number of wal files and filenames(using `pgmoneta_get_files()`)
- The current wal file would be the last filename

cc: @Jubilee101 @jesperpedersen

**Comment by Jubilee101** [comment]
Hi, there is no need to do that. pgmoneta is always streaming WAL segments. Read the code in https://github.com/pgmoneta/pgmoneta/blob/main/src/libpgmoneta/wal.c. You will find the latest wal segment it's currently streaming, along with corresponding file name. So no need to go through the entire wal archive directory. Good luck:)

**Comment by shikharish** [comment]
@Jubilee101 Opened a PR.
