### ISSUE TITLE
Expose WAL log sequence number (pgmoneta_current_wal_lsn) to Prometheus

### ISSUE THREAD

**Issue by lenhat509** [pgmoneta/pgmoneta#207]
Display the current Log Sequence Number of the WAL on Prometheus metrics

```
pgmoneta_current_wal_1sn{server="primary", LSN="0/19FCACO"} 1
 ```

**Comment by jesperpedersen** [comment]
It should be

```
pgmoneta_current_wal_lsn{server="primary", lsn="0/19FCACO"} 1
```

**Comment by jesperpedersen** [comment]
If LSN is unknown then it should say `lsn="0/0"`

**Comment by lenhat509** [comment]
> It should be
> 
> ```
> pgmoneta_current_wal_lsn{server="primary", lsn="0/19FCACO"} 1
> ```
I fixed the comment. Thanks.
