### ISSUE TITLE
[-Werror=maybe-uninitialized] in main.c

### ISSUE THREAD

**Issue by GuChad369** [pgmoneta/pgmoneta#209]
When installing pgmoneta using the Git source, there are some errors in the source code after running the 'make' command.

```
`[ 91%] Building C object src/CMakeFiles/pgmoneta-bin.dir/main.c.o
In function ‘init_replication_slots’,
    inlined from ‘main’ at /usr/local/pgmoneta/src/main.c:626:20:
/usr/local/pgmoneta/src/main.c:1938:41: error: ‘slot_status’ may be used uninitialized [-Werror=maybe-uninitialized]
 1938 |          if (create_slot && slot_status == SLOT_NOT_FOUND && strlen(config->servers[srv].wal_slot) > 0)
/usr/local/pgmoneta/src/main.c: In function ‘main’:
/usr/local/pgmoneta/src/main.c:1848:8: note: ‘slot_status’ was declared here
 1848 |    int slot_status;
      |        ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/pgmoneta-bin.dir/build.make:76: src/CMakeFiles/pgmoneta-bin.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:174: src/CMakeFiles/pgmoneta-bin.dir/all] Error 2
make: *** [Makefile:156: all] Error 2`
```

**Comment by jesperpedersen** [comment]
What compiler and compiler version are you using ?

**Comment by GuChad369** [comment]
Fedora 38 
gcc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)
I just initiated it with SLOT_NOT_FOUND and ran successfully!

I researched and created a guide tailored for a new beginner to install this application on a Fedora 38 virtual machine. I compiled the guide by combining several references from the Git documentation. 

hope it helpful

[install.md](https://github.com/pgmoneta/pgmoneta/files/14593854/install.md)

**Comment by jesperpedersen** [comment]
Can you send a pull request for this ?

Although it should be

```
int slot_status = INCORRECT_SLOT_TYPE;
```
 
I think your document could be a good start for a `doc/DEVELOPERS.md` file... So, can you send a pull request for that too ?

**Comment by jesperpedersen** [comment]
Remember to add yourself to the `AUTHORS` file as well...

**Comment by GuChad369** [comment]
sorry for twice PR
