### ISSUE TITLE
Expose backup throughput to prometheus

### ISSUE THREAD

**Issue by GuChad369** [pgmoneta/pgmoneta#218]
To enhance user convenience, a new feature is being added to monitor backup throughput and expose it to Prometheus. 

The basic idea is to calculate the throughput by dividing the size of each server backup by the time taken to complete the backup.

**Comment by 1366240475** [comment]
@GuChad369 I'm working on it.

**Comment by GuChad369** [comment]
@1366240475 This has been completed with [PR #214](https://github.com/pgmoneta/pgmoneta/pull/214), which you can review.

**Comment by GuChad369** [comment]
@1366240475 This has been completed with [210](https://github.com/pgmoneta/pgmoneta/pull/210), which you can review.
