### ISSUE TITLE
Developer guide

### ISSUE THREAD

**Issue by GuChad369** [pgmoneta/pgmoneta#219]
A new guide for beginners to set up the `pgmoneta` work environment and explore its features for the Fodera 38 OS.
- Combine information from several documents into one for easier fellow.
- Update some new default configurations.

**Comment by 1366240475** [comment]
@GuChad369 I'd like to do it!

**Comment by GuChad369** [comment]
If you would like to contribute, the common approach is to first create an issue, and then reference that issue number in the PR message.
