### ISSUE TITLE
Add minor version label in backup.info

### ISSUE THREAD

**Issue by l32zhao** [pgmoneta/pgmoneta#221]
**Problem Statement**

When making a full backup, pgmoneta currently records the PostgreSQL server's major version in the backup.info file but does not include the minor version. Including only the major version (e.g., 16) provides incomplete information about the PostgreSQL server version used during the backup. This can lead to ambiguity, especially when trying to restore backups, as minor version differences can also be critical to ensuring compatibility and understanding the exact environment the backup was taken from.

**Additional information**

Consider backward compatibility with existing tools or scripts that parse the backup.info file. Adding a new label should not break existing parsing logic but should be documented.

**Comment by 1366240475** [comment]
I have committed and pulled the request linking to this issue.

**Comment by jesperpedersen** [comment]
Please, add yourself to `AUTHORS` as well

**Comment by l32zhao** [comment]
> Please, add yourself to `AUTHORS` as well

Done. Thanks for reminding me!
