### ISSUE TITLE
Force `master-key` to abort if user files exist

### ISSUE THREAD

**Issue by fluca1978** [pgmoneta/pgmoneta#230]
Similarly to the issue <https://github.com/agroal/pgagroal/issues/425>, when `master-key` is issued all the existing files that use encryption are invalidated, and this could result in confusion for the users.
It would be better to make the program to abort in the case there are files in place, so that the user knows that the files must be manually removed and she has to enter user values again.

**Comment by Jubilee101** [comment]
Hi @fluca1978 , thanks, I'll take it on pgmoneta side.
