### ISSUE TITLE
Lack of Feedback for Illegal Passwords in Setting Master Key for pgmoneta-admin

### ISSUE THREAD

**Issue by l32zhao** [pgmoneta/pgmoneta#239]
# Problem

I discovered that when attempting to set an illegal password for the **master key** of pgmoneta-admin, there is no indication or feedback provided.

# Solution

To address this issue, it would be beneficial to include informative messaging, such as specifying the acceptable length of passwords, when setting the master key for pgmoneta-admin.

**Comment by l32zhao** [comment]
Here is a screenshot of this problem:
![1711045362186](https://github.com/pgmoneta/pgmoneta/assets/29018475/fa78e2ee-ceff-424e-ae54-84e342ca4a61)

**Comment by Jubilee101** [comment]
Hi there, would you like to work on this? Maybe just print out the reason why the validation fails. It should be quite useful, thanks for bringing this up.
