### ISSUE TITLE
Use replication slot to determine starting LSN and timeline ID for WAL streaming

### ISSUE THREAD

**Issue by l32zhao** [pgmoneta/pgmoneta#245]
## Description
Currently, when the WAL archive directory is empty, pgmoneta uses the current LSN of the PostgreSQL server as the starting point for WAL streaming. This is done by issuing the IDENTIFY_SYSTEM command. However, for PostgreSQL 15 and above, we can leverage the replication slot to obtain the starting LSN and timeline ID more accurately.

## Task
Implement the feature to query the replication slot using the READ_REPLICATION_SLOT command from the PostgreSQL replication protocol. This command should be issued before attempting to use IDENTIFY_SYSTEM as a last resort when the archive directory is empty.

**Comment by l32zhao** [comment]
@Jubilee101 I'm working on it, please assign the issue to me : )

**Comment by Jubilee101** [comment]
Good luck! Let us know if you have questions.

**Comment by Jubilee101** [comment]
Hey @l32zhao just want to follow up on this. Let us know if there are problems~

**Comment by jesperpedersen** [comment]
@l32zhao Any updates ?

**Comment by l32zhao** [comment]
I just created a pull request for you guys to review.

Besides, I want to apologize for my recent absence and delay in contributing to the project because I was back in my home country for a month and couldn't keep up with my tasks.
