### ISSUE TITLE
Password Generation Function Generates Strings Containing Configuration File Comment Characters

### ISSUE THREAD

**Issue by joanjeremiah** [pgmoneta/pgmoneta#262]
I noticed the generate_password function in the admin.c file is currently generating passwords that may contain characters '#' and ';'. These characters pose a problem when used in passwords intended for configuration files, as they could inadvertently trigger comment recognition ( as an inline comment ) within the configuration syntax.

Possible solutions include excluding '#' and ';' characters from the list of characters used in password generation. @jesperpedersen Can I implement this solution?

**Comment by jesperpedersen** [comment]
Yes
