### ISSUE TITLE
Initial manual 

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#265]
This need to be under `doc/manual/` and it could likely be based on `pandoc` and `markdown` files to compile into `.pdf` and `.html`

**Comment by GuChad369** [comment]
- Is this manual about setting up the environment?
- What is the structure of the directory?

**Comment by jesperpedersen** [comment]
We could look at doing something similar to https://github.com/EnterpriseDB/barman/tree/master/doc/manual just with `cmake`.

Better ideas are welcomed !

**Comment by GuChad369** [comment]
- Should we integrate CMake directly into our project, or should we keep it separate in the manual directory? 
- This way, if a user wants to generate it, they can do so; otherwise, we won't generate it by default.

**Comment by jesperpedersen** [comment]
I don't understand - it should be part of the standard `cd build/ && cmake .. && make` setup

**Comment by GuChad369** [comment]
Okay, thanks. I'll work on it.
