### ISSUE TITLE
Security: Create functions for SHA checksums for a file

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#266]
Create functions

```
int
pgmoneta_create_sha256_file(char* path, char** sha);

int
pgmoneta_create_sha384_file(char* path, char** sha);

int
pgmoneta_create_sha512_file(char* path, char** sha);
```

using the OpenSSL API

**Comment by jesperpedersen** [comment]
We likely need one for CRC32C as well...

**Comment by shikharish** [comment]
Hello, I would like to work on this issue.

**Comment by jesperpedersen** [comment]
@shikharish Go for it

**Comment by shikharish** [comment]
@jesperpedersen What is the role `pgmoneta_generate_file_sha256_hash()` in `security.c`?

**Comment by jesperpedersen** [comment]
@shikharish It is part of the foundation of https://github.com/pgmoneta/pgmoneta/issues/267

**Comment by shikharish** [comment]
I did not quite get that. Where would `pgmoneta_create_sha256_file(char* path, char** sha)` be used? In the `verify` command in #267? Will the implementation be similar to `pgmoneta_generate_file_sha256_hash()`?

**Comment by jesperpedersen** [comment]
@shikharish Do you have a work branch for this ?

**Comment by jesperpedersen** [comment]
Related #291

**Comment by shikharish** [comment]
@jesperpedersen I had created the functions(similar to the already existing `pgmoneta_create_sha256_file(char* path, char** sha)`, but later realised that the functions used there were deprecated in OpenSSL version 3.0. So I am working on updating it.

Please check my current work [here](https://github.com/shikharish/pgmoneta/blob/6d367d6e2d613b4c5b7a69827e7efc76245b28fe/src/libpgmoneta/security.c#L2864).

**Comment by jesperpedersen** [comment]
You can look here https://www.openssl.org/docs/man3.1/man3/SHA256.html

**Comment by jesperpedersen** [comment]
We just need to support OpenSSL 1.1 and OpenSSL 3.x

**Comment by shikharish** [comment]
@jesperpedersen Don't we need a function for SHA224 as well?

**Comment by jesperpedersen** [comment]
Sure, we can add that as well - just to have the option
