### ISSUE TITLE
Prometheus: Logging

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#268]
Add metrics for logging statements for INFO+

```
#HELP pgmoneta_logging_info Number of INFO logging statements
#TYPE pgmoneta_logging_info gauge
pgmoneta_logging_info <number>

#HELP pgmoneta_logging_warn Number of WARN logging statements
#TYPE pgmoneta_logging_warn gauge
pgmoneta_logging_warn <number>

...
```

and so  on

**Comment by joanjeremiah** [comment]
Can I work on this task? @jesperpedersen

**Comment by jesperpedersen** [comment]
@joanjeremiah Yes

**Comment by joanjeremiah** [comment]
I plan to:

1. Increment log level counters in the pgmoneta_log_line function.
2. Store these counters in the config struct as an array.
3. Use this array in prometheus.c's general_information function to log these metrics in the specified manner.

@jesperpedersen  Could you confirm if this approach sounds good, or if there are any adjustments you'd recommend?

Thanks!

**Comment by jesperpedersen** [comment]
Yes, this sound good, so lets see how the patch looks

**Comment by jesperpedersen** [comment]
How is this going ?

**Comment by jesperpedersen** [comment]
@joanjeremiah Ping ?

**Comment by joanjeremiah** [comment]
I started working on this. Couldn't find the time to continue.  Will work on it, this weekend.

**Comment by jesperpedersen** [comment]
@joanjeremiah Still ok on this ?

**Comment by joanjeremiah** [comment]
> @joanjeremiah Still ok on this ?

Sorry, couldnt find time to complete this.

**Comment by jesperpedersen** [comment]
@joanjeremiah Do you want to be unassigned on it ? It isn't a big task so you should be able to complete it quickly - you can do it

**Comment by joanjeremiah** [comment]
> @joanjeremiah Do you want to be unassigned on it ? It isn't a big task so you should be able to complete it quickly - you can do it

Kindly unassign me

**Comment by jesperpedersen** [comment]
@joanjeremiah No problem
