### ISSUE TITLE
Support WAL shipping to remote server

### ISSUE THREAD

**Issue by HazemRawi** [pgmoneta/pgmoneta#274]
I will implement a complete workflow that handles shipping WAL segments to remote storage engines.

This process will start by executing the command 

`pgmoneta-cli -c pgmoneta.conf wal-shipping [<server>|all]`

till we have a copy of WAL segments in the remote server.

- [ ]  SSH storage engine

- [ ]  S3 storage engine 

- [ ]  Azure storage engine

**Comment by jesperpedersen** [comment]
This should be done automatically.

Please, use https://github.com/pgmoneta/pgmoneta/discussions/54 for discussion.

Rejected
