### ISSUE TITLE
Manual: User guide

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#281]
Implement improvements to the user guide

**Comment by jesperpedersen** [comment]
Ideally we should have some include functionality, like https://github.com/steindani/pandoc-include

Or, should we move to AsciiDoc ?

**Comment by jesperpedersen** [comment]
We need a better template for the generated documentation,

https://lornajane.net/posts/2023/generating-a-nice-looking-pdf-with-pandoc
https://github.com/Wandmalfarbe/pandoc-latex-template

**Comment by jesperpedersen** [comment]
@GuChad369 Cc:

**Comment by GuChad369** [comment]
Do we need to specify the installation process for the Eisvogel package, or is it sufficient to mention that the package is required? Several steps are involved in adding the package for use.

**Comment by GuChad369** [comment]
> Ideally we should have some include functionality, like https://github.com/steindani/pandoc-include
> 
> Or, should we move to AsciiDoc ?

I'm unsure which option is preferable. The first requires using a script to facilitate the inclusion of components. We would need to add the script to `doc/manual/` directory. 

On the other hand, if we opt for AsciiDoc, `pandoc` cannot convert AsciiDoc directly into PDF.

**Comment by jesperpedersen** [comment]
Ok, I mentioned AsciiDoc because it has file inclusion built-in, but building a PDF is more important

**Comment by GuChad369** [comment]
> We have to figure out how the needed components are installed - otherwise we will have to supply those in-tree under `doc/support`

I have successfully used the Eisvogel package to generate a better PDF, but it may require extra effort to install the necessary components.

**Comment by jesperpedersen** [comment]
We need to test with RHEL8, RHEL9, FreeBSD and when building a RPM so just keep that in mind

**Comment by GuChad369** [comment]
The problem is that installing the full TeX Live package directly might cause a timeout on GitHub due to the large size of the package. 

Alternatively, specifying only the needed packages could require installing them one by one. 

Which approach do you think would be better?

**Comment by jesperpedersen** [comment]
If you see https://github.com/pgmoneta/pgmoneta/commit/ae9764c93f03adceff969ab7d32d8e371116bc73 - it is an example of a good "include" (`AUTHORS`)

**Comment by jesperpedersen** [comment]
We have about a month to try - lets start with the simplest way...

**Comment by GuChad369** [comment]
> We have about a month to try - lets start with the simplest way...

Indeed, for the manual, it's a long-term project. We will need to continuously improve it over time.

**Comment by jesperpedersen** [comment]
Out-of-tree components is of course the best solution... if the versions align, and can generate the same output

**Comment by jesperpedersen** [comment]
We also have to figure out how to share files between both manuals - like `user-08-acknowledgement.en.md`

**Comment by jesperpedersen** [comment]
I think I'm happy with the file structure of the manuals now - 10 "pre" chapters, and 10 "post" chapters
