### ISSUE TITLE
Security: Create functions for CRC32x checksums for a file

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#291]
Create functions

```
int
pgmoneta_create_crc32c_file(char* path, char** crc);

int
pgmoneta_create_crc32c_buffer(void* buffer, size_t size, char** crc);
```

This need to be done with AVX instructions

**Comment by shikharish** [comment]
I would like to work on this.

**Comment by jesperpedersen** [comment]
You likely need to stick to AVX2 - see https://en.wikipedia.org/wiki/Advanced_Vector_Extensions - or SSE...

I would just begin with a basic implementation, and then we can add compiler switches like `#ifdef HAVE_AVX2` to have a more optimized version.

There are a lot of articles around it, like

* https://news.ycombinator.com/item?id=32305900
* https://github.com/topics/crc32?l=c

Remember you have to develop this code yourself...

**Comment by shikharish** [comment]
@jesperpedersen There is a CRC32C implementation already present in `hashmap.c`. Do we want to implement a similar function here? It uses SSE4.2 instructions.
