### ISSUE TITLE
CLI: annotation command

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#305]
Add a CLI annotation command that will store key / value pairs in a JSON structure under the `CUSTOM` key in the `backup.info` file

**Comment by l32zhao** [comment]
Please, assign me

**Comment by jesperpedersen** [comment]
@l32zhao Have fun with this task !

**Comment by jesperpedersen** [comment]
You need an `add` and a `remove` subcommand

**Comment by jesperpedersen** [comment]
@l32zhao Are you ok on this ?

**Comment by vishu1089** [comment]
hey, I see the issue is still open, can you brief me on this and assign?

**Comment by jesperpedersen** [comment]
@vishu1089 You need to add a `COMMENT=` to `backup.info` (`info.c`), and then a new command to `cli.c` with an `add` and `remove` subcommand.

So,

```
pgmoneta-cli annotate primary <backup_id> add mycomment
```

would lead to 

```
COMMENT=mycomment
```

in `backup.info` -- there can be multiple comments so those are separated by `,`

Thanks for taking this on !

**Comment by jesperpedersen** [comment]
@vishu1089 Once you have a work branch submit a work-in-progress pull request.

https://github.com/pgmoneta/pgmoneta/blob/main/doc/DEVELOPERS.md can help...

**Comment by vishu1089** [comment]
Understood

**Comment by vishu1089** [comment]
I have checked, there is no file name as backup.info
do i need to create it?

**Comment by jesperpedersen** [comment]
@vishu1089 It will be created during the `backup` - run through the tutorials to get to know the configuration and CLI commands

**Comment by vishu1089** [comment]
Let’s connect for basic understanding?

**Comment by jesperpedersen** [comment]
Feel free to write a mail to Haoran and me

**Comment by jesperpedersen** [comment]
@vaishnavi-2901 Are you ok on this ?

**Comment by vaishnavi-2901** [comment]
yes, need time to unnderstand this well

**Comment by jesperpedersen** [comment]
See `AUTHORS` or `git log` for contact information...

**Comment by jesperpedersen** [comment]
@vaishnavi-2901 Are you doing ok on this ?

**Comment by jesperpedersen** [comment]
@vaishnavi-2901 How is it going ?
