### ISSUE TITLE
Integrate extension

### ISSUE THREAD

**Issue by GuChad369** [pgmoneta/pgmoneta#319]
- Add the test suite from [pgmoneta_ext](https://github.com/pgmoneta/pgmoneta_ext/pull/11) to install the extension.
- Create `extension.h|.c` that will call the extension functions.

**Comment by GuChad369** [comment]
To integrate the test suite, we can simply copy it from `pgmoneta_ext`.

For `extension.h|.c`, how can we make `pgmoneta` call the extension functions? 

Do we need to use a shell script command?

**Comment by jesperpedersen** [comment]
No, you need to use the wire protocol to query the extension - see https://www.postgresql.org/docs/16/protocol-message-formats.html and `message.h|.c`

**Comment by jesperpedersen** [comment]
You can send multiple pull requests for this in order to get started

**Comment by GuChad369** [comment]
For the test suite, do I need to modify the tests to include the installation of `pgmoneta`, or just copy the test suite from `pgmoneta_ext`?

I would like to first send a pull request to handle the test suite. 

After that, I will send another pull request to handle the modifications to `extension.h|.c`.

**Comment by GuChad369** [comment]
When using `pgmoneta-admin` to set the master key, if a master key already exists, it will cause a segmentation fault. 

I am not sure what the problem might be; could it be an issue with the source code? I tried to solve it, but I have no clue about this.

```sh
sudo -u pgmoneta /tmp/pgmoneta/build/src/pgmoneta-admin master-key -P pgmonetamasterkey
```

<img width="1189" alt="Screenshot 2024-06-25 at 12 00 24 PM" src="https://github.com/pgmoneta/pgmoneta/assets/113565433/a8c8f339-ca83-4b06-ad07-f4979ef07832">


With this problem, we can't set up the script to auto-configure `pgmoneta`.

**Comment by jesperpedersen** [comment]
Does it happen locally for you as well ? In case with `-P` or `-g`

**Comment by GuChad369** [comment]
> Does it happen locally for you as well ? In case with `-P` or `-g`

Yeah, you are right. Without the `-P` option, there is no segmentation fault. It seems to be a problem with the source code.

<img width="1194" alt="Screenshot 2024-06-25 at 12 58 50 PM" src="https://github.com/pgmoneta/pgmoneta/assets/113565433/87d9750e-2c60-4642-a889-a2f50500dc0c">

**Comment by jesperpedersen** [comment]
Why is there a `master.key` - it should only be run once

**Comment by jesperpedersen** [comment]
#320

**Comment by GuChad369** [comment]
> Why is there a `master.key` - it should only be run once

Normally, it should run just once, and this problem will not occur.

We want to create a script to install and configure `pgmoneta` automatically, as we need to test it with different versions of PostgreSQL. 

After testing one version, we want to try another version of PostgreSQL. This requires us to reinstall and reconfigure `pgmoneta` each time. 

To ensure our script can handle various situations, we need to consider the possibility that pgmoneta was already installed previously.

**Comment by jesperpedersen** [comment]
Yeah, you can either reuse the pgmoneta files between the different PostgreSQL, or remove them and recreate them

**Comment by GuChad369** [comment]
I did some research and read the related documents. To achieve the `extension.h|.c`, I am trying to use `ssl_write_message` and `ssl_read_message` to call the pgsql command. Do you think this idea is correct?

**Comment by jesperpedersen** [comment]
Yes, you can look at the different messages in `message.c` to see how the server is called

**Comment by jesperpedersen** [comment]
You can look at how the https://github.com/pgexporter/pgexporter/ and https://github.com/pgexporter/pgexporter_ext projects interact
