### ISSUE TITLE
Backup labels in list-backup command broken?

### ISSUE THREAD

**Issue by shikharish** [pgmoneta/pgmoneta#322]
All backup labels are same as the first one in list-backup command:
```
./pgmoneta-cli -c pgmoneta.conf list-backup primary
Server           : primary
Number of backups: 3
Backup           :
                   20240626222708 (Backup: 8.7 MB Restore: 60.8 MB WAL: 80 MB Delta: 0 Retain: No Valid: Yes)
                   20240626222708 (Backup: 5.0 MB Restore: 60.8 MB WAL: 80 MB Delta: 0 Retain: No Valid: Yes)
                   20240626222708 (Backup: 5.0 MB Restore: 60.8 MB WAL: 80 MB Delta: 0 Retain: No Valid: Yes)
```

The build is the latest commit on main branch.
System info: "Linux  6.6.31-linuxkit aarch64 GNU/Linux" Ubuntu 24.04

**Comment by shikharish** [comment]
I am running pgmoneta on Ubuntu 24.04 on a VM running on MacOS 13.5

**Comment by Jubilee101** [comment]
Thanks for bringing this up. We are working on new manifest feature and I might have broken something. This should be fixed in the next patch.

**Comment by Jubilee101** [comment]
Can you pull and check? @shikharish

**Comment by shikharish** [comment]
Fixed. Thanks.
