### ISSUE TITLE
Get extra files from the server

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#328]
Use the `pgmoneta_ext` extension to get extra files / directories (recursive) from the PostgreSQL server instance.

Of course there has to be read priviledge for it for the user.

A test case could be writing something to `/tmp` and then getting it.

Everything should go into an `/extras` directory under the backup, and be displayed as part of the `info` command.

Configuration should go under each server - separated by `,` like

```
extra = /tmp/myfile,/tmp/mydir/*,/tmp/mydirs/**
```

should translate into

```
cd extras/
/tmp/myfile
/tmp/mydir/*
/tmp/mydirs/**
```

**Comment by jesperpedersen** [comment]
@GuChad369 Can you take this ?

**Comment by GuChad369** [comment]
Of course, I will try, but it may take a long time to finish.

I suppose we need to first complete `extension.h|.c` which will be necessary.

**Comment by jesperpedersen** [comment]
Yeah, and we need the test suite in first - it isn't a problem
