### ISSUE TITLE
CLI: Compress / decompress

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#345]
Add `compress` and `decompress` commands in the CLI such that files can be handled

**Comment by GuChad369** [comment]
The desired behavior for this issue is that when the user types "compress," all extra files will be compressed, and when the user types "decompress," all files will be decompressed. 

Alternatively, does the user need to pass a variable to specify a single file to be compressed or decompressed?

**Comment by GuChad369** [comment]
I tried to follow `cli.c` and `management.c` to understand how encryption is implemented, but I ended up getting confused and couldn't find the exact code for executing encryption. How do the CLI commands work in our project? Which files should I focus on? 

Any ideas would be appreciated. Thanks!

**Comment by jesperpedersen** [comment]
If you want to work on this then you are oon the correct track - it is more or less a copy'n'paste starting from `cli.c` and through `management.c`.

So, where ever it says `encrypt` / `decrypt` - copy and rename `compress` / `decompress`

Do you want to be assigned ?

**Comment by GuChad369** [comment]
Okay, I can try this.

However, I haven't found the exact location where the encryption function is called, so I still don't understand how it works.

**Comment by jesperpedersen** [comment]
`cli.c` -> `management.c` -> `main.c` -> `aes.c`

**Comment by jesperpedersen** [comment]
So, you need to `if () / elseif()` or `switch` in `main.c` and then call the correct function in the configured compression method, so

* bzip2_compression.h
* gzip_compression.h
* lz4_compression.h
* zstandard_compression.h

**Comment by GuChad369** [comment]
Okay. Thanks for your help.
