### ISSUE TITLE
Management: Client side translation of numeric fields

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#366]
Some fields are numeric, f.ex.

```
"Valid": 1,
```

which could be

```
"Valid": "Yes",
```

after the translation

**Comment by Jubilee101** [comment]
Boolean values are printed as true/false, maybe that'll do for valid. We still need to translate stuff like hash algorithm though

**Comment by jesperpedersen** [comment]
Valid is a 3-value thing - "Unknown", "No" or "Yes"

**Comment by ashu3103** [comment]
@jesperpedersen Kindly assign me this issue.

**Comment by jesperpedersen** [comment]
```
"Valid": "no",
```

which should be "Yes"

We should consider an untranslated `-F raw` format...
