### ISSUE TITLE
Support escape characters in JSON

### ISSUE THREAD

**Issue by Jubilee101** [pgmoneta/pgmoneta#373]
Support escape character in [pgmoneta_json_parse_string](https://github.com/pgmoneta/pgmoneta/blob/c3c903b7996c59856817f63117c42e7f2b1dd061/src/include/json.h#L216) and [pgmoneta_json_to_string](https://github.com/pgmoneta/pgmoneta/blob/c3c903b7996c59856817f63117c42e7f2b1dd061/src/include/json.h#L236). I think what we need is mostly `"\""` and `"\'"` but it would be nice if we support the rest, if not too hard.

Note that for to_string this should only apply to `FORMAT_JSON`, for `FORMAT_TEXT` there's no need since strings are not wrapped in double quotation marks. Checkout [string_to_string_cb](https://github.com/pgmoneta/pgmoneta/blob/c3c903b7996c59856817f63117c42e7f2b1dd061/src/libpgmoneta/value.c#L411) for details.

**Comment by Jubilee101** [comment]
Hey @ashu3103, let me know if you are interested in this.

**Comment by ashu3103** [comment]
> Hey @ashu3103, let me know if you are interested in this.

Sure

**Comment by ashu3103** [comment]
@Jubilee101, I have started working on this,

Just one thing to confirm, we only need escape characters support for the values of the json fields right?
Or does it has to be implemented for the keys

Thanks

**Comment by jesperpedersen** [comment]
Did you check the spec - https://www.json.org/json-en.html ?

**Comment by ashu3103** [comment]
> Did you check the spec - https://www.json.org/json-en.html ?

Very helpful, Thanks for sharing

**Comment by jesperpedersen** [comment]
@Jubilee101 Can you take this one

**Comment by jesperpedersen** [comment]
@ashu3103 Submit your PR, and Haoran will work with you on it

**Comment by Jubilee101** [comment]
> Just one thing to confirm, we only need escape characters support for the values of the json fields right?
Or does it has to be implemented for the keys as well

Hmm, I would prefer support for both key and value, unless we have problems with supporting keys, in that case let us know and we can discuss what's best.

It's mostly for handling escape characters when parsing a json string, you need to be able to identify them and parse each of them into corresponding character. In terms of printing the most important thing is to treat `"` specially -- print it out as `\"` to avoid ambiguity, and as for the rest just use your judgement to decide what to do. Note that it's just for printing, when a value is stored in a string and not printed out, it should always be one char per escape character.

We should probably reject string with `"` but not `\"` during parsing, as well as illegal usage of `\`.

Make sure that the json object can be converted to string and parsed back to the same json object -- with keys and values of exactly the same bytes. We use `pgmoneta_json_clone` a lot which depends on this. Let us know if there are problems achieving that.

Any questions or better ideas just let me know, thanks for working on this!

**Comment by Jubilee101** [comment]
> Note that it's just for printing, when a value is stored in a string and not printed out, it should always be one char per escape character.

> Make sure that the json object can be converted to string and parsed back to the same json object -- with keys and values of exactly the same bytes. We use pgmoneta_json_clone a lot which depends on this. Let us know if there are problems achieving that.

Hmm, maybe we need a separate `pgmoneta_json_serialize` apart from `pgmoenta_json_to_string` to distinguish the case where we want to print out a string with simply sending it over network.

**Comment by ashu3103** [comment]
> > Just one thing to confirm, we only need escape characters support for the values of the json fields right?
> > Or does it has to be implemented for the keys as well
> 
> Hmm, I would prefer support for both key and value, unless we have problems with supporting keys, in that case let us know and we can discuss what's best.
> 

Okay will implement for both :)

> It's mostly for handling escape characters when parsing a json string, you need to be able to identify them and parse each of them into corresponding character. In terms of printing the most important thing is to treat `"` specially -- print it out as `\"` to avoid ambiguity, and as for the rest just use your judgement to decide what to do. Note that it's just for printing, when a value is stored in a string and not printed out, it should always be one char per escape character.
> 
Yeah, I was also thinking along the same lines.

> We should probably reject string with `"` but not `\"` during parsing, as well as illegal usage of `\`.
> 
To cater the illegal usage, we can reject the string if it contains anything after '\' which is not an escape character.

> Make sure that the json object can be converted to string and parsed back to the same json object -- with keys and values of exactly the same bytes. We use `pgmoneta_json_clone` a lot which depends on this. Let us know if there are problems achieving that.
> 
Sure!

> Any questions or better ideas just let me know, thanks for working on this!
My initial draft PR is ready, I will push it after some testing and we can discuss it from there.

**Comment by ashu3103** [comment]
> > Note that it's just for printing, when a value is stored in a string and not printed out, it should always be one char per escape character.
> 
> > Make sure that the json object can be converted to string and parsed back to the same json object -- with keys and values of exactly the same bytes. We use pgmoneta_json_clone a lot which depends on this. Let us know if there are problems achieving that.
> 
> Hmm, maybe we need a separate `pgmoneta_json_serialize` apart from `pgmoenta_json_to_string` to distinguish the case where we want to print out a string with simply sending it over network.
> 
> Or simpler, adding a FORMAT_JSON_SERIALIZE in `pgmoenta_json_to_string` would be a better idea.

Let me recon on it.

**Comment by Jubilee101** [comment]
> I will recon this idea and then we can discuss.

On second(?) thought you may not need it, as long as to_string and parsing have aligned logic, and the original string still has one byte per special character. I'm just tossing ideas around, feel free to decide what's actually necessary.
