### ISSUE TITLE
Management: Support compression

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#376]
Support NONE, and all the different compression methods.

The CLI can use `-C 0|none...` and the same method will be used for the return payload

**Comment by GuChad369** [comment]
I remember I implemented `pgmoneta-cli compress file_path`. So for this issue, the desired behavior is to make it work when the user calls `pgmoneta-cli -C zstd file_path` to perform the same task. If the user calls `pgmoneta-cli -C none file_path`, it will use the default method for compression. Is my understanding correct?

**Comment by jesperpedersen** [comment]
No, this is for the protocol, so

```
pgmoneta-cli -C zstd status
```

will give the output - but on the wire it has been compressed

**Comment by GuChad369** [comment]
Apologies, I'm not clear on this. Could you explain in more detail or provide an example?

**Comment by jesperpedersen** [comment]
You need to compress the JSON document, so add a `-C zstd` option -- all of them -- then compress the JSON document, and send it as the string.

Of course on the other side you need to uncompress to get the JSON document back

**Comment by GuChad369** [comment]
What I need to do is modify the function `pgmoneta_management_write_json` and also add the option in `cli.c`.

```c
int
pgmoneta_management_write_json(SSL* ssl, int socket, struct json* json)
{
   ... 

   s = pgmoneta_json_to_string(json, FORMAT_JSON, NULL, 0);

   ...

   if(-C){
      compress_buffer = compress_s_output(...)
      base64 = encode(compress_buffer)
   }

   if (write_string("pgmoneta-cli", ssl, socket, base64))
   {
      goto error;
   }

   ...
}
```

is this correct?

**Comment by Jubilee101** [comment]
> Apologies, I'm not clear on this. Could you explain in more detail or provide an example?

Sorry we are not so clear about the context. Since #344 we've upgraded our protocol between cli and management. Recall how we used to send parameters and options from cli input to management on main, it's one parameter at a time. Now they are all wrapped inside a json as the payload, which will be converted to string and sent to main. And on the other side the json string gets parsed and the parameters and command are extracted.

This has clear benefits as it simplified the management and made it easier to extend. Also if you try commands now you'll see they all support json output.

But clearly it brings bandwidth overhead of sending the json string. That's where you come in to help, by compressing the string before sending it, and decompressing after receiving it. I think you are already getting the gist of it.

**Comment by GuChad369** [comment]
So, we compress it in the function `pgmoneta_management_write_json` and decompress it in the function `pgmoneta_management_read_json`.

**Comment by Jubilee101** [comment]
> So, we compress it in the function pgmoneta_management_write_json and decompress it in the function pgmoneta_management_read_json.

I believe that's the idea. Note that this isn't mandatory, we try to find fun tasks for contributors, including ourselves. Feel free to browse issues and find something interesting to work on, or come up with your own ideas. And don't worry about GSoC, you are doing great. We are just worried that you get bored. Some coding work occasionally to free yourself from the exploration for a moment might help.

**Comment by GuChad369** [comment]
Okay, thanks for your help. Another question about `compression` and `encryption`: what is the meaning of these two variables in the function? Are they related to the `CLI`, or are they intended for another task?

**Comment by Jubilee101** [comment]
> Okay, thanks for your help. Another question about compression and encryption: what is the meaning of these two variables in the function? Are they related to the CLI, or are they intended for another task?

I think you are refering to `MANAGEMENT_COMPRESSION_NONE` and `MANAGEMENT_ENCRYPTION_NONE`. They are just enums indicating the compression and encrytion types, currently it's just NONE meaning no compression/encryption when sending the commands, you are supposed add more macros indicating more types as you progress.

**Comment by GuChad369** [comment]
Okay, I have a clearer understanding of this issue now. I’ll give it a try, and if I have more questions, I’ll ask for help.

**Comment by GuChad369** [comment]
There is an unused error at `/pgmoneta/src/libpgmoneta/walfile/wal_reader.c:209:17`:  
```
error: unused variable ‘bytes_read’
```

**Comment by GuChad369** [comment]
How can we make the function `write_uint8("pgmoneta-cli", ssl, socket, compression)` to retrieve the compression value from `cli.c`? Is there an example of how this process works?

**Comment by GuChad369** [comment]
I found all the compression functions for file types. So, to support this, is it allowed to create a new function to compress/decompress for strings?

**Comment by jesperpedersen** [comment]
Yes, you can create new functions for the memory buffer work

**Comment by GuChad369** [comment]
Right now, I am using the following definitions, where `WARN` means that if the user inputs an incorrect method, it will return a warning message and ask for another try. `NONE` is for the default compression method when the user inputs `-C none`. However, I have a question: if the user does not input the option at all, how should we handle the process? Will it avoid compression, or should it also use the default method to compress? If we decide to always use the default compression method, I think we can remove the `NONE` option.
```c
#define MANAGEMENT_COMPRESSION_NONE 0
#define MANAGEMENT_COMPRESSION_GZIP 1
#define MANAGEMENT_COMPRESSION_ZSTD 2
#define MANAGEMENT_COMPRESSION_LZ4 3
#define MANAGEMENT_COMPRESSION_BZIP2 4
#define MANAGEMENT_COMPRESSION_WARN 10
```

**Comment by jesperpedersen** [comment]
`NONE` is no compression and the default.

If an unknown option is specified, then the CLI should just error out

**Comment by jesperpedersen** [comment]
`-F sdafasf` should result in an error, but it is a separate issue that you can open and file a PR for

**Comment by GuChad369** [comment]
So, when the user inputs `-C none`, we should skip the compression process. However, when the user does not input `-C` at all, we should use the default method to compress the JSON. Is that what you mean?

**Comment by jesperpedersen** [comment]
`-C none` is the same as not doing `-C` since `none` is the default

**Comment by GuChad369** [comment]
ok, thanks

**Comment by GuChad369** [comment]
Today, I implemented the first compression function and tested it. The compression function works. However, I encountered a very weird error, and I'm a bit confused at this point.

When I call the command, it results in a segmentation fault. The main reason is: `Get string: (null)`.
```log
[pgmoneta@fedora-linux-38 ~]$ pgmoneta-cli -c pgmoneta.conf -F json -C gz status
Stard compress
End compress
Start encode
End encode
Encode data string: H4sIAAAAAAACA6vmUlBQ8khNTEktUrJSqAbygHznnMzUvJKw1KLizPw8oLCSgZ6hqZ6Bkg5UOj83NzEvBShhDhXxLy0pKC0BChhCBUIyc1OLSxJzC0C6jQyMTAwNDEwNLY0tjCyUgCpqQcqUglILS4GqQPbWctUCALYYVeCKAAAA
Get string: (null)
Start decode
Segmentation fault (core dumped)
```

But in the pgmoneta log, I can actually see that the content is being retrieved.
```log
Get string: H4sIAAAAAAACAy2NOwqAMBBEe08RthbZiFG0tbETROwDbhEw8ZdUkru7gZTz5g3zFULARHqnBwbxceI8Hoac3+h5zekYA1ZSVQhlrk9rtdu56DKZg7+CZyAzWI2l12t7pXWNdSMRleybVvXARkwaLHQHttJvLOIPgIvP54oAAAA=
Start decode
End decode
Start decompress
Decompression successful! Decompressed string: {
  "Header": {
    "ClientVersion": "0.15.0",
    "Command": 7,
    "Output": 1,
    "Timestamp": "20241005194659"
  },
  "Request": {}
}
End decompress
Stard compress
End compress
Start encode
End encode
Encode data string: 
2024-10-05 19:46:59 INFO  status.c:198 Status (Elapsed: 00:00:00)
```

**Comment by GuChad369** [comment]
I have written a gzip function to compress the string into a buffer, and I’ve also implemented the encode and decode functions using base64. I need help with the functions `pgmoneta_management_response_ok` and `pgmoneta_management_response_error`. How can I retrieve the `compress_method` in these two functions to pass it into `pgmoneta_management_write_json`? Right now, the `-C` option only works one way; it cannot send a response back correctly.

[commit](https://github.com/pgmoneta/pgmoneta/compare/main...GuChad369:pgmoneta:compression)

```log
[pgmoneta@fedora-linux-38 ~]$ pgmoneta-cli -c pgmoneta.conf -F json -C gz status
Original string: {
  "Header": {
    "ClientVersion": "0.15.0",
    "Command": 7,
    "Output": 1,
    "Timestamp": "20241005195537"
  },
  "Request": {}
}
Stard compress
End compress
Compression successful! Compressed size: 128 bytes
Start encode
End encode
Encode data string: H4sIAAAAAAACAy2NOwqAMBBEe08RthbZqEG0tbETROwDbhEw8ZdUkru7gZTz5g3zFULARHqnBwbxceI8Hoac3+h5zekYA1ZSVQhlrk9rtdu56DKZg7+CZyAzWI2l12t7pXWNdSsRleyVajpgIyYNFroDW+k3FvEH/nngLYoAAAA=
Get string: (null)
Start decode
Segmentation fault (core dumped)

```

```log
Get string: H4sIAAAAAAACAy2NOwqAMBBEe08RthbZqEG0tbETROwDbhEw8ZdUkru7gZTz5g3zFULARHqnBwbxceI8Hoac3+h5zekYA1ZSVQhlrk9rtdu56DKZg7+CZyAzWI2l12t7pXWNdSsRleyVajpgIyYNFroDW+k3FvEH/nngLYoAAAA=
Start decode
End decode
Start decompress
Decompression successful! Decompressed string: {
  "Header": {
    "ClientVersion": "0.15.0",
    "Command": 7,
    "Output": 1,
    "Timestamp": "20241005195537"
  },
  "Request": {}
}
End decompress
Original string: {
  "Header": {
    "ClientVersion": "0.15.0",
    "Command": 7,
    "Output": 1,
    "Timestamp": "20241005195537"
  },
  "Outcome": {
    "Status": true,
    "Time": "00:00:00"
  },
  "Request": {},
  "Response": {
    "FreeSpace": 866230272,
    "NumberOfServers": 1,
    "Offline": false,
    "ServerVersion": "0.15.0",
    "Servers": [
      {
        "HotStandbySize": 0,
        "NumberOfBackups": 1,
        "RetentionDays": 7,
        "RetentionMonths": -1,
        "RetentionWeeks": -1,
        "RetentionYears": -1,
        "Server": "primary",
        "ServerSize": 25452544,
        "Workers": 0
      }
    ],
    "TotalSpace": 1024401408,
    "UsedSpace": 25452544,
    "Workers": 0
  }
}
Stard compress
End compress
Compression successful! Compressed size: 0 bytes
Start encode
End encode
Encode data string: 
2024-10-05 19:55:37 INFO  status.c:198 Status (Elapsed: 00:00:00)

```

**Comment by jesperpedersen** [comment]
You pass the parameters out through `read_json` - and then back in again.

https://github.com/pgmoneta/pgmoneta/blob/main/src/main.c#L826 (out)
https://github.com/pgmoneta/pgmoneta/blob/main/src/main.c#L874 (in)

**Comment by jesperpedersen** [comment]
`... (..., compression, encryption, pyl);`
