### ISSUE TITLE
Management: Support encryption

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#377]
Support NONE, and all the different encryption methods.

The CLI can use `-E 0|none..`. and the same method will be used for the return payload

**Comment by jesperpedersen** [comment]
@GuChad369 Can you take this one ?

**Comment by jesperpedersen** [comment]
I don't think we need to support all algorithms so

* aes (aes-256)
* aes-256
* aes-192
* aes-128

that uses `CBC`

**Comment by GuChad369** [comment]
Absolutely. I’ll start working on this issue, and if I encounter any problems, I’ll seek help.

**Comment by GuChad369** [comment]
So, the core functions to encrypt a string to a buffer will be:

- `aes_256_cbc()`
- `aes_192_cbc()`
- `aes_128_cbc()`

What's the difference between `aes (aes-256)` and `aes-256`?

**Comment by jesperpedersen** [comment]
Great !

`aes` is just a short-cut for `aes-256`, so both are the same -- `none` is default.

You can just do `..., uint8_t compression, uint8_t encryption, ...`
