### ISSUE TITLE
Compilation errors: Unused Variable and fread Error Handling

### ISSUE THREAD

**Issue by HazemRawi** [pgmoneta/pgmoneta#394]
When I attempt to build pgmoneta from source, I encounter the following two errors:

1.     error: unused variable
2.     error: ignoring return value of ‘fread’

![image](https://github.com/user-attachments/assets/d39f3630-2031-4b36-b52e-d0e324aacde6)

To address these errors, I can check if the number of bytes read is less than zero. If it is, I will log the error using `pgmoneta_log_error("")`;."

**Comment by jesperpedersen** [comment]
Yes, see how error handling is done with `fread`. Which compiler are you using ?

@sh-soltanpour Cc:

**Comment by HazemRawi** [comment]
**gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0**
