### ISSUE TITLE
Add pgmoneta-walinfo CLI to parse and display WAL file

### ISSUE THREAD

**Issue by sh-soltanpour** [pgmoneta/pgmoneta#396]
**Is your feature request related to a problem? Please describe.**

Now that we have WAL reading and parsing functionality in place, we want to have a command-line interface (CLI). This CLI will support more complex features in the future, but in this issue, I want to focus on creating the CLI itself and the ability to parse the given file and display it in a prettified human-readable format. 
The display feature must be able to work offline.

**Comment by jesperpedersen** [comment]
There are two options here.

1) Single file then it can go into `src/walinfo.c`
2) Multiple files then it goes into `contrib/walinfo/`

Former it easier, but latter is likely more future proof

**Comment by jesperpedersen** [comment]
You can use `FORMAT_COMPACT` to get started although it is not readable for humans...

@Jubilee101 We can think about about this...
