### ISSUE TITLE
walinfo: Start / End LSN

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#412]

**Comment by jesperpedersen** [comment]
@sh-soltanpour Could you take a look at this ? It seems like the calculations are off, in some cases

```
Heap2 | 0/6FE8350 | 0/6FE838B | 59 | 59 | 759 | cutoff xid 0 flags 0x03 blkref #0: rel 1663/16391/16404 forknum 2 blk 0 blkref #1: rel 1663/16391/16404 forknum 0 blk 13212
Heap2 | 0/6FE9CC8 | 0/6FE9FDF | 791 | 791 | 759 | 7 tuples flags 0x22 blkref #0: rel 1663/16391/16404 forknum 0 blk 13213
```

From `pgbench -i -s 10` setup

**Comment by sh-soltanpour** [comment]
hmm in the first glance, I can see that this formula is not always correct. For example, look at this output of pg_waldump:
```rmgr: XLOG        len (rec/tot):     49/    73, tx:        752, lsn: 0/030274D0, prev 0/030274A0, desc: FPI , blkref #0: rel 1663/16391/2619 fork vm blk 0 FPW```

0/030274D0 - 0/030274A0 = 0x30 (48 in decimal) but the len is 49.

**Comment by sh-soltanpour** [comment]
I think we need to check how pg_waldump is doing the calculation and do the same thing here.
