### ISSUE TITLE
Metrics: Time and speed

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#423]
We should add Prometheus metrics about how much time is spent in each step of a backup - including how that translates into MB/s processing.

Metrics:
* Total
* Base backup
* Compression
* Encryption
* Linking
* Manifest
* Remote

so each "area" will translate into 2 Prometheus metrics.

Look at `wf_backup` @ https://github.com/pgmoneta/pgmoneta/blob/main/src/libpgmoneta/workflow.c#L208 for the different stages.

The information could be saved in `backup.info`

**Comment by jesperpedersen** [comment]
@shikharish Can you take this one ?

**Comment by shikharish** [comment]
Yes, please assign me.

**Comment by jesperpedersen** [comment]
You could look into

```
#TYPE gauge
XYZ_total_lastime{} 8

#TYPE gauge
XYZ_total_mbs{} 87.6

#HELP Provide a histogram for the total backup time -- run-time only, data isn't persisted 
#TYPE histogram
XYZ_total{}
```

**Comment by shikharish** [comment]
@jesperpedersen Currently we calculate time in seconds for any time-related metric. For better accuracy, I think we should use milliseconds, etc. How about I change all time metrics to double from int, like 1.25sec instead of 1sec?

**Comment by shikharish** [comment]
That way the MB/s speed will be accurate too.

**Comment by jesperpedersen** [comment]
@shikharish Yeah, feel free to change the data types - as long as it is reflected in the Prometheus interface... I don't think we need like 8 digits ... X.YYY is more than enough.

Maybe there are some best practices in Prometheus interfaces for this area...
