### ISSUE TITLE
pgmoneta: error while loading shared libraries: /usr/local/lib64/libpgmoneta.so.0: invalid ELF header

### ISSUE THREAD

**Issue by skpupil** [pgmoneta/pgmoneta#57]
Today I cloned the pgmoneta frome github. Then I did like this in my docker container(centos8):
`     cd pgmoneta
      mkdir build
      cd build/
      cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
      make
      make install
`
When I run `pgmoneta`, I met this: `pgmoneta: error while loading shared libraries: /usr/local/lib64/libpgmoneta.so.0: invalid ELF header`. I run `git log`. It showed the last commmit id is `a3a673274fdf921ba82bed08ec27e66cd825e818`.
Then I tried the release version 0.56. This problem disappeared.

**Comment by jesperpedersen** [comment]
That looks like a compiler/linker error - especially since your 0.5.6 install worked.

Did you check with `file` and `ldd` ?

As CentOS doesn't have a stable ABI anymore - maybe you want to use Rocky Linux instead.

**Comment by skpupil** [comment]
I checked with file and ldd between 0.5.6 and the cloned version. There was nothing abnormal. I still think one commit after the 0.5.6 release version caused this problem. Last commmit id is a3a673274fdf921ba82bed08ec27e66cd825e818.

**Comment by jesperpedersen** [comment]
That sounds like a compiler problem, as that commit just suppress compiler warnings

**Comment by skpupil** [comment]
I tried Rocky Linux instead refer to https://github.com/jesperpedersen/podman-pgsql/tree/master/pgsql14-pgmoneta-rocky8/Dockerfile. It still didn't work.

**Comment by jesperpedersen** [comment]
Did you try to use the RPMs from yum.postgresql.org ?

**Comment by skpupil** [comment]
This problem was fixed. The problem was because I mapped my windows machine directory to docker virtual machine, and the .so was stored into my windows host machine, so it caused the elf problem.

**Comment by skpupil** [comment]
Fixed. thx.
