### ISSUE TITLE
MacOS X support

### ISSUE THREAD

**Issue by omerfruk** [pgmoneta/pgmoneta#96]
**Describe the bug**

Whene I install pgmoneta whit `make` command in macos. I am getting error like this 
>[  0%] Built target man
Consolidate compiler generated dependencies of target pgmoneta
[  2%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/aes.c.o
/usr/local/pgmoneta/src/libpgmoneta/aes.c:60:28: error: use of undeclared identifier 'DT_DIR'
      if (entry->d_type == DT_DIR)
                           ^
/usr/local/pgmoneta/src/libpgmoneta/aes.c:144:28: error: use of undeclared identifier 'DT_REG'
      if (entry->d_type == DT_REG)
                           ^
/usr/local/pgmoneta/src/libpgmoneta/aes.c:223:28: error: use of undeclared identifier 'DT_DIR'
      if (entry->d_type == DT_DIR)
                           ^
3 errors generated.
make[2]: *** [src/CMakeFiles/pgmoneta.dir/libpgmoneta/aes.c.o] Error 1
make[1]: *** [src/CMakeFiles/pgmoneta.dir/all] Error 2
make: *** [all] Error 2

How can ı solve this problem. thenks

**Comment by jesperpedersen** [comment]
MacOS isn't supported by the build system at the moment.

All necessary changes should be within `src/CMakeLists.txt` using the `Darwin` system identifier. Can you work on that?

**Comment by jesperpedersen** [comment]
You could try the `CMAKE_OSX_SYSROOT` route first, see

https://stackoverflow.com/questions/10165335/can-cmake-specify-the-base-sdk-on-mac-os-x

if that helps... We need the system libraries from the MacOS SDK linked into the pgmoneta library in order for it to work.

**Comment by 2010YOUY01** [comment]
MacOS support has been done on a similar project `pgagroal`, you can use this PR as reference if you would like to build and run `pgmoneta` on MacOS X
https://github.com/agroal/pgagroal/pull/351

**Comment by jesperpedersen** [comment]
@HazemRawi Go for it ! See @2010YOUY01's comment - it should be the same

**Comment by HazemRawi** [comment]
I wanted to understand the whole process so I'm playing with CMakeLists.txt of pgagroal & pgmoneta as well as reading some specific pages of the documentation of CMake.
I'll be back soon.
